/*
 * parser_utils.hpp - Utilities for parser data from GFA.
 *
 * MIT License (see LICENSE in the repository root).
 * Copyright (c) 2020-2026 Juri Kuronen
*/
#pragma once

#include <cassert>
#include <cstddef>
#include <string>

#include "common/utils/Exception.hpp"
#include "gfa_parser/core/Orientation.hpp"

namespace PANGWES {
namespace ParserUtils {

// Returns the DNA complement of `base`.
inline char complement_base(char base) {
    switch (base) {
        case 'A': return 'T';
        case 'C': return 'G';
        case 'G': return 'C';
        case 'T': return 'A';
        case 'a': return 't';
        case 'c': return 'g';
        case 'g': return 'c';
        case 't': return 'a';
        default: throw Exception(ErrorCode::INVALID_DATA, "unknown base: ", base);
    }
}

/*
 * Returns true if the oriented suffix of `from_sequence` matches the oriented prefix of `to_sequence` for `overlap`
 * bases.
*/
inline bool is_exact_overlap(const std::string& from_sequence,
                             const std::string& to_sequence,
                             Orientation from_orientation,
                             Orientation to_orientation,
                             std::size_t overlap)
{
    assert(overlap > 0 && "cannot check exact overlap with zero overlap");

    if (from_sequence.size() <= overlap || to_sequence.size() <= overlap) {
        return false;
    }

    const auto from_overlap_start = from_sequence.size() - overlap;

    // Returns the base at `index` after applying the segment orientation.
    const auto oriented_base = [](const std::string& sequence, Orientation orientation, std::size_t index) {
        return orientation == Orientation::PLUS
               ? sequence[index]
               : complement_base(sequence[sequence.size() - 1 - index]);
    };

    for (std::size_t idx = 0; idx < overlap; ++idx) {
        if (oriented_base(from_sequence, from_orientation, from_overlap_start + idx) !=
            oriented_base(to_sequence, to_orientation, idx))
        {
            return false;
        }
    }

    return true;
}

// Structure for separating reference assembly and contig sequence names encoded in a path name.
struct ParsedPathName {
    std::string reference_name;
    std::string sequence_name;
};

// Extracts reference and sequence name from a path name generated by Cuttlefish.
inline ParsedPathName parse_cuttlefish_path_name(const std::string& path_name) {
    static const std::string reference_start_identifier = "Reference:";
    static const std::string sequence_start_identifier = "_Sequence:";

    const auto reference_start_idx = path_name.find(reference_start_identifier);
    const auto sequence_start_idx = path_name.find(sequence_start_identifier);

    if (reference_start_idx == std::string::npos ||
        sequence_start_idx == std::string::npos ||
        sequence_start_idx < reference_start_idx)
    {
        throw Exception(ErrorCode::INVALID_DATA, "failed to parse path name: ", path_name);
    }

    const auto reference_start = reference_start_idx + reference_start_identifier.size();

    const auto reference_length = sequence_start_idx - reference_start;
    const auto sequence_start = sequence_start_idx + sequence_start_identifier.size();

    return ParsedPathName{
        path_name.substr(reference_start, reference_length),
        path_name.substr(sequence_start)
    };
}

} // namespace ParserUtils
} // namespace PANGWES
