PROJECT           := unitig_distance

# Keep this include order.
include ../mk/config.mk
include ../mk/common.mk
include ../mk/flags.mk
include ../mk/lint.mk
include ../mk/sources.mk
include ../mk/rules.mk
include ../mk/targets.mk
include ../mk/version.mk

# End-to-end tests runner and results verification script for `unitig_distance`.
RUNE2ETESTS       := $(PROJECTDIR)/scripts/run_unitig_distance_e2e_tests.sh
TESTRUNNERSCRIPT  := $(PROJECTDIR)/scripts/verify_unitig_distance_results.pl
