PROJECT           := common

# Keep this include order.
include ../mk/config.mk
include ../mk/common.mk
include ../mk/flags.mk
include ../mk/lint.mk
include ../mk/sources.mk
include ../mk/rules.mk
include ../mk/targets.mk
include ../mk/version.mk
