PROJECT           := gfa_parser

# Keep this include order.
include ../mk/config.mk
include ../mk/common.mk
include ../mk/flags.mk
include ../mk/lint.mk
include ../mk/sources.mk
include ../mk/rules.mk
include ../mk/targets.mk
include ../mk/version.mk

# End-to-end tests runner and results verification script for `gfa_parser`.
RUNE2ETESTS       := $(PROJECTDIR)/scripts/run_gfa_parser_e2e_tests.sh
TESTRUNNERSCRIPT  := $(PROJECTDIR)/scripts/verify_gfa_parser_results.pl
